version: '3'
services:
  node-app:
    build: .
    image: jeremyfriesen1/node-repo:latest
    ports:
      - "1234:1234"
    depends_on:
      - flask-app

  flask-app:
    build: ./flask_api
    image: jeremyfriesen1/flask-repo:latest
    ports:
      - "5000:5000"
